[package]
name = "pacman"
version = "1.0.0"
authors = ["Warhorst <46809804+Warhorst@users.noreply.github.com>", "QPCrummer"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.14.2"
rand = "0.8.5"
bevy_asset_preload = {git = "https://github.com/Warhorst/bevy_asset_preload.git", rev = "b39d956"}
bevy_sprite_sheet = {git = "https://github.com/Warhorst/bevy_sprite_sheet.git", rev = "0f36ca6"}
pad = { git = "https://github.com/Warhorst/pad.git", rev = "fe7e97a", features = ["bevy"] }
serde = "1.0.216"
serde_json = "1.0.133"
bevy_window_icon = "0.4.0"
ffmpeg-next = "7.1.0"